name: Mauricio's homepage
theme: jekyll-theme-midnight
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
title: 
description: 
# Site Author
author:
  name             : "Mauricio Gamonal"
  avatar           : "Perfil-PennState.jpeg"
  bio              : "PhD Candidate at Penn State"
  location         : "State College, PA"
  email            : "mgamonal@psu.edu"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : 
  foursquare       :
  github           : "mauricio-gamonal"
  google_plus      :
  keybase          :
  instagram        : "cosmo.mauri"
  lastfm           :
  linkedin         : 
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          : "cosmo_mauri"
  vine             :
  weibo            :
  xing             :
  youtube          :
  # Custom author fields follow
  arxiv            : "gamonal_m_1"
  orcid            : "0000-0002-0677-4926"
  inspire          : "M.Gamonal.1"
  google-scholar   : "ENjqVhcAAAAJ"
  mastodon         :
    handle         : 
    instance       : 

comments:
  giscus:
    enabled: true
    repo: "mauricio-gamonal/mauricio-gamonal.github.io"
    repo_id: "R_kgDOMM6a9w"
    category: "Announcements"
    category_id: "DIC_kwDOMM6a984CjmiM"
    mapping: "pathname"
    reactions_enabled: "1"
    theme: "light_high_contrast"
    input-position: "top"
    lang: "en"
    crossorigin: "anonymous"
